Update error-correct-pass2 and correct-reads without moving them from the sandbox
dib-lab/khmer pull request #1744
Opened 2017-07-10 19:53 UTC by wltrimbl

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make clean diff-cover` If it introduces new functionality in
  `scripts/` is it tested?
- [ ] `make format diff_pylint_report cppcheck doc pydocstyle` Is it well
  formatted?
- [ ] Did it change the command-line interface? Only backwards-compatible
  additions are allowed without a major version increment. Changing file
  formats also requires a major version number increment.
- [ ] For substantial changes or changes to the command-line interface, is it
  documented in `CHANGELOG.md`? See [keepachangelog](http://keepachangelog.com/)
  for more details.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?
- [ ] Do the changes respect streaming IO? (Are they
  tested for streaming IO?)

2017-07-10 23:18 UTC, wltrimbl commented
These changes do not introduce any new functionality; these merely make the two (wonderful) error-correction scripts work with khmer 2.1.2 and add tests that run most of the code included.  
Ready for review.

2017-07-11 04:36 UTC, standage requested changes
Thanks for the PR!

This looks good for the most part. I've made a comments and questions, but these relate to minor issues that should be simple to address / comment on. I'll be happy to merge after your response.

2017-07-11 04:36 UTC, standage commented on tests/test_sandbox_scripts.py
> +    except:
Is this block trying to ensure the script fails on this data set? This is much more clearly declared with pytest's "raises" construct. Something like the following should work.

```python
with pytest.raises(ValueError) as ve:
    result = function_that_should_fail(bad_input)
assert 'expected error message' in str(ve)
```

If I've misunderstood, please clarify.

2017-07-11 04:36 UTC, standage commented on tests/test_sandbox_scripts.py
> +    infile = utils.get_test_data('paired.fq')
Looks like `infile` is redefined here.

2017-07-11 04:36 UTC, standage commented on sandbox/correct-reads.py
> +          file=sys.stderr)
Bless you for the tedious and thankless work towards Python 2/3 compatibility! 👍

2017-07-11 13:39 UTC, standage approved these changes

2017-07-11 13:39 UTC, standage commented
Thanks for the updates. Will merge when the CI build passes.

2017-07-11 13:58 UTC, merged

2017-07-11 13:59 UTC, standage commented
Thanks, @wltrimbl!

2017-07-11 14:00 UTC, ctb commented
yes, thank you!!